version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./audit_logs:/app/audit_logs
    environment:
      - TARGET_SERVER=httpbin.org
      - TARGET_PORT=80
      - USE_CACHE=false
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge